### ISSUE TITLE
Flutter web

### ISSUE THREAD

**Issue by jasonlaw** [martin-robert-fink/oauth_client_demo#1]
Nice work!
Could you please also add for the web?
Thanks.

**Comment by martin-robert-fink** [comment]
Hi Jason -

Glad you found some of this helpful.  It's unlikely I will add web to this.  The underlying architecture assumes a hard separation between client and server (mobile/desktop, not browser).  As such, I use dart:io (WebSockets) which flutter web doesn't allow.

If someone is able to do a PR and add that, it would be great.

Martin
